#ifndef COLORS_H
#define COLORS_H
#pragma once

#define BLACK_ON_BLACK 0 // Черный на черном
#define BLUE_ON_BLACK 1 // Синий на черном
#define GREEN_ON_BLACK 2 // Зеленый на черном
#define CYAN_ON_BLACK 3 // Голубой на черном
#define RED_ON_BLACK 4 // Красный на черном
#define MAGENTA_ON_BLACK 5 // Магента на черном
#define BROWN_ON_BLACK 6 // Коричневый на черном
#define LIGHT_GRAY_ON_BLACK 7 // Светло-серый на черном
#define DARK_GRAY_ON_BLACK 8 // Темно-серый на черном
#define LIGHT_BLUE_ON_BLACK 9 // Светло-синий на черном
#define LIGHT_GREEN_ON_BLACK 10 // Светло-зеленый на черном
#define LIGHT_CYAN_ON_BLACK 11 // Светло-голубой на черном
#define LIGHT_RED_ON_BLACK 12 // Светло-красный на черном
#define LIGHT_MAGENTA_ON_BLACK 13 // Светло-магентовый на черном
#define YELLOW_ON_BLACK 14 // Желтый на черном
#define WHITE_ON_BLACK 15 // Белый на черном

#define BLACK_ON_BLUE 16 // Черный на синем
#define BLUE_ON_BLUE 17 // Синий на синем
#define GREEN_ON_BLUE 18 // Зеленый на синем
#define CYAN_ON_BLUE 19 // Голубой на синем
#define RED_ON_BLUE 20 // Красный на синем
#define MAGENTA_ON_BLUE 21 // Магента на синем
#define BROWN_ON_BLUE 22 // Коричневый на синем
#define LIGHT_GRAY_ON_BLUE 23 // Светло-серый на синем
#define DARK_GRAY_ON_BLUE 24 // Темно-серый на синем
#define LIGHT_BLUE_ON_BLUE 25 // Светло-синий на синем
#define LIGHT_GREEN_ON_BLUE 26 // Светло-зеленый на синем
#define LIGHT_CYAN_ON_BLUE 27 // Светло-голубой на синем
#define LIGHT_RED_ON_BLUE 28 // Светло-красный на синем
#define LIGHT_MAGENTA_ON_BLUE 29 // Светло-магентовый на синем
#define YELLOW_ON_BLUE 30 // Желтый на синем
#define WHITE_ON_BLUE 31 // Белый на синем

#define BLACK_ON_GREEN 32 // Черный на зеленом
#define BLUE_ON_GREEN 33 // Синий на зеленом
#define GREEN_ON_GREEN 34 // Зеленый на зеленом
#define CYAN_ON_GREEN 35 // Голубой на зеленом
#define RED_ON_GREEN 36 // Красный на зеленом
#define MAGENTA_ON_GREEN 37 // Магента на зеленом
#define BROWN_ON_GREEN 38 // Коричневый на зеленом
#define LIGHT_GRAY_ON_GREEN 39 // Светло-серый на зеленом
#define DARK_GRAY_ON_GREEN 40 // Темно-серый на зеленом
#define LIGHT_BLUE_ON_GREEN 41 // Светло-синий на зеленом
#define LIGHT_GREEN_ON_GREEN 42 // Светло-зеленый на зеленом
#define LIGHT_CYAN_ON_GREEN 43 // Светло-голубой на зеленом
#define LIGHT_RED_ON_GREEN 44 // Светло-красный на зеленом
#define LIGHT_MAGENTA_ON_GREEN 45 // Светло-магентовый на зеленом
#define YELLOW_ON_GREEN 46 // Желтый на зеленом
#define WHITE_ON_GREEN 47 // Белый на зеленом

#define BLACK_ON_CYAN 48 // Черный на голубом
#define BLUE_ON_CYAN 49 // Синий на голубом
#define GREEN_ON_CYAN 50 // Зеленый на голубом
#define CYAN_ON_CYAN 51 // Голубой на голубом
#define RED_ON_CYAN 52 // Красный на голубом
#define MAGENTA_ON_CYAN 53 // Магента на голубом
#define BROWN_ON_CYAN 54 // Коричневый на голубом
#define LIGHT_GRAY_ON_CYAN 55 // Светло-серый на голубом
#define DARK_GRAY_ON_CYAN 56 // Темно-серый на голубом
#define LIGHT_BLUE_ON_CYAN 57 // Светло-синий на голубом
#define LIGHT_GREEN_ON_CYAN 58 // Светло-зеленый на голубом
#define LIGHT_CYAN_ON_CYAN 59 // Светло-голубой на голубом
#define LIGHT_RED_ON_CYAN 60 // Светло-красный на голубом
#define LIGHT_MAGENTA_ON_CYAN 61 // Светло-магентовый на голубом
#define YELLOW_ON_CYAN 62 // Желтый на голубом
#define WHITE_ON_CYAN 63 // Белый на голубом

#define BLACK_ON_RED 64 // Черный на красном
#define BLUE_ON_RED 65 // Синий на красном
#define GREEN_ON_RED 66 // Зеленый на красном
#define CYAN_ON_RED 67 // Голубой на красном
#define RED_ON_RED 68 // Красный на красном
#define MAGENTA_ON_RED 69 // Магента на красном
#define BROWN_ON_RED 70 // Коричневый на красном
#define LIGHT_GRAY_ON_RED 71 // Светло-серый на красном
#define DARK_GRAY_ON_RED 72 // Темно-серый на красном
#define LIGHT_BLUE_ON_RED 73 // Светло-синий на красном
#define LIGHT_GREEN_ON_RED 74 // Светло-зеленый на красном
#define LIGHT_CYAN_ON_RED 75 // Светло-голубой на красном
#define LIGHT_RED_ON_RED 76 // Светло-красный на красном
#define LIGHT_MAGENTA_ON_RED 77 // Светло-магентовый на красном
#define YELLOW_ON_RED 78 // Желтый на красном
#define WHITE_ON_RED 79 // Белый на красном

#define BLACK_ON_MAGENTA 80 // Черный на магентовом
#define BLUE_ON_MAGENTA 81 // Синий на магентовом
#define GREEN_ON_MAGENTA 82 // Зеленый на магентовом
#define CYAN_ON_MAGENTA 83 // Голубой на магентовом
#define RED_ON_MAGENTA 84 // Красный на магентовом
#define MAGENTA_ON_MAGENTA 85 // Магента на магентовом
#define BROWN_ON_MAGENTA 86 // Коричневый на магентовом
#define LIGHT_GRAY_ON_MAGENTA 87 // Светло-серый на магентовом
#define DARK_GRAY_ON_MAGENTA 88 // Темно-серый на магентовом
#define LIGHT_BLUE_ON_MAGENTA 89 // Светло-синий на магентовом
#define LIGHT_GREEN_ON_MAGENTA 90 // Светло-зеленый на магентовом
#define LIGHT_CYAN_ON_MAGENTA 91 // Светло-голубой на магентовом
#define LIGHT_RED_ON_MAGENTA 92 // Светло-красный на магентовом
#define LIGHT_MAGENTA_ON_MAGENTA 93 // Светло-магентовый на магентовом
#define YELLOW_ON_MAGENTA 94 // Желтый на магентовом
#define WHITE_ON_MAGENTA 95 // Белый на магентовом

#define BLACK_ON_BROWN 96 // Черный на коричневом
#define BLUE_ON_BROWN 97 // Синий на коричневом
#define GREEN_ON_BROWN 98 // Зеленый на коричневом
#define CYAN_ON_BROWN 99 // Голубой на коричневом
#define RED_ON_BROWN 100 // Красный на коричневом
#define MAGENTA_ON_BROWN 101 // Магента на коричневом
#define BROWN_ON_BROWN 102 // Коричневый на коричневом
#define LIGHT_GRAY_ON_BROWN 103 // Светло-серый на коричневом
#define DARK_GRAY_ON_BROWN 104 // Темно-серый на коричневом
#define LIGHT_BLUE_ON_BROWN 105 // Светло-синий на коричневом
#define LIGHT_GREEN_ON_BROWN 106 // Светло-зеленый на коричневом
#define LIGHT_CYAN_ON_BROWN 107 // Светло-голубой на коричневом
#define LIGHT_RED_ON_BROWN 108 // Светло-красный на коричневом
#define LIGHT_MAGENTA_ON_BROWN 109 // Светло-магентовый на коричневом
#define YELLOW_ON_BROWN 110 // Желтый на коричневом
#define WHITE_ON_BROWN 111 // Белый на коричневом

#define BLACK_ON_LIGHT_GRAY 112 // Черный на светло-сером
#define BLUE_ON_LIGHT_GRAY 113 // Синий на светло-сером
#define GREEN_ON_LIGHT_GRAY 114 // Зеленый на светло-сером
#define CYAN_ON_LIGHT_GRAY 115 // Голубой на светло-сером
#define RED_ON_LIGHT_GRAY 116 // Красный на светло-сером
#define MAGENTA_ON_LIGHT_GRAY 117 // Магента на светло-сером
#define BROWN_ON_LIGHT_GRAY 118 // Коричневый на светло-сером
#define LIGHT_GRAY_ON_LIGHT_GRAY 119 // Светло-серый на светло-сером
#define DARK_GRAY_ON_LIGHT_GRAY 120 // Темно-серый на светло-сером
#define LIGHT_BLUE_ON_LIGHT_GRAY 121 // Светло-синий на светло-сером
#define LIGHT_GREEN_ON_LIGHT_GRAY 122 // Светло-зеленый на светло-сером
#define LIGHT_CYAN_ON_LIGHT_GRAY 123 // Светло-голубой на светло-сером
#define LIGHT_RED_ON_LIGHT_GRAY 124 // Светло-красный на светло-сером
#define LIGHT_MAGENTA_ON_LIGHT_GRAY 125 // Светло-магентовый на светло-сером
#define YELLOW_ON_LIGHT_GRAY 126 // Желтый на светло-сером
#define WHITE_ON_LIGHT_GRAY 127 // Белый на светло-сером

#define BLACK_ON_DARK_GRAY 128 // Черный на темно-сером
#define BLUE_ON_DARK_GRAY 129 // Синий на темно-сером
#define GREEN_ON_DARK_GRAY 130 // Зеленый на темно-сером
#define CYAN_ON_DARK_GRAY 131 // Голубой на темно-сером
#define RED_ON_DARK_GRAY 132 // Красный на темно-сером
#define MAGENTA_ON_DARK_GRAY 133 // Магента на темно-сером
#define BROWN_ON_DARK_GRAY 134 // Коричневый на темно-сером
#define LIGHT_GRAY_ON_DARK_GRAY 135 // Светло-серый на темно-сером
#define DARK_GRAY_ON_DARK_GRAY 136 // Темно-серый на темно-сером
#define LIGHT_BLUE_ON_DARK_GRAY 137 // Светло-синий на темно-сером
#define LIGHT_GREEN_ON_DARK_GRAY 138 // Светло-зеленый на темно-сером
#define LIGHT_CYAN_ON_DARK_GRAY 139 // Светло-голубой на темно-сером
#define LIGHT_RED_ON_DARK_GRAY 140 // Светло-красный на темно-сером
#define LIGHT_MAGENTA_ON_DARK_GRAY 141 // Светло-магентовый на темно-сером
#define YELLOW_ON_DARK_GRAY 142 // Желтый на темно-сером
#define WHITE_ON_DARK_GRAY 143 // Белый на темно-сером

#define BLACK_ON_LIGHT_BLUE 144 // Черный на светло-синем
#define BLUE_ON_LIGHT_BLUE 145 // Синий на светло-синем
#define GREEN_ON_LIGHT_BLUE 146 // Зеленый на светло-синем
#define CYAN_ON_LIGHT_BLUE 147 // Голубой на светло-синем
#define RED_ON_LIGHT_BLUE 148 // Красный на светло-синем
#define MAGENTA_ON_LIGHT_BLUE 149 // Магента на светло-синем
#define BROWN_ON_LIGHT_BLUE 150 // Коричневый на светло-синем
#define LIGHT_GRAY_ON_LIGHT_BLUE 151 // Светло-серый на светло-синем
#define DARK_GRAY_ON_LIGHT_BLUE 152 // Темно-серый на светло-синем
#define LIGHT_BLUE_ON_LIGHT_BLUE 153 // Светло-синий на светло-синем
#define LIGHT_GREEN_ON_LIGHT_BLUE 154 // Светло-зеленый на светло-синем
#define LIGHT_CYAN_ON_LIGHT_BLUE 155 // Светло-голубой на светло-синем
#define LIGHT_RED_ON_LIGHT_BLUE 156 // Светло-красный на светло-синем
#define LIGHT_MAGENTA_ON_LIGHT_BLUE 157 // Светло-магентовый на светло-синем
#define YELLOW_ON_LIGHT_BLUE 158 // Желтый на светло-синем
#define WHITE_ON_LIGHT_BLUE 159 // Белый на светло-синем

#define BLACK_ON_LIGHT_GREEN 160 // Черный на светло-зеленом
#define BLUE_ON_LIGHT_GREEN 161 // Синий на светло-зеленом
#define GREEN_ON_LIGHT_GREEN 162 // Зеленый на светло-зеленом
#define CYAN_ON_LIGHT_GREEN 163 // Голубой на светло-зеленом
#define RED_ON_LIGHT_GREEN 164 // Красный на светло-зеленом
#define MAGENTA_ON_LIGHT_GREEN 165 // Магента на светло-зеленом
#define BROWN_ON_LIGHT_GREEN 166 // Коричневый на светло-зеленом
#define LIGHT_GRAY_ON_LIGHT_GREEN 167 // Светло-серый на светло-зеленом
#define DARK_GRAY_ON_LIGHT_GREEN 168 // Темно-серый на светло-зеленом
#define LIGHT_BLUE_ON_LIGHT_GREEN 169 // Светло-синий на светло-зеленом
#define LIGHT_GREEN_ON_LIGHT_GREEN 170 // Светло-зеленый на светло-зеленом
#define LIGHT_CYAN_ON_LIGHT_GREEN 171 // Светло-голубой на светло-зеленом
#define LIGHT_RED_ON_LIGHT_GREEN 172 // Светло-красный на светло-зеленом
#define LIGHT_MAGENTA_ON_LIGHT_GREEN 173 // Светло-магентовый на светло-зеленом
#define YELLOW_ON_LIGHT_GREEN 174 // Желтый на светло-зеленом
#define WHITE_ON_LIGHT_GREEN 175 // Белый на светло-зеленом

#define BLACK_ON_LIGHT_CYAN 176 // Черный на светло-голубом
#define BLUE_ON_LIGHT_CYAN 177 // Синий на светло-голубом
#define GREEN_ON_LIGHT_CYAN 178 // Зеленый на светло-голубом
#define CYAN_ON_LIGHT_CYAN 179 // Голубой на светло-голубом
#define RED_ON_LIGHT_CYAN 180 // Красный на светло-голубом
#define MAGENTA_ON_LIGHT_CYAN 181 // Магента на светло-голубом
#define BROWN_ON_LIGHT_CYAN 182 // Коричневый на светло-голубом
#define LIGHT_GRAY_ON_LIGHT_CYAN 183 // Светло-серый на светло-голубом
#define DARK_GRAY_ON_LIGHT_CYAN 184 // Темно-серый на светло-голубом
#define LIGHT_BLUE_ON_LIGHT_CYAN 185 // Светло-синий на светло-голубом
#define LIGHT_GREEN_ON_LIGHT_CYAN 186 // Светло-зеленый на светло-голубом
#define LIGHT_CYAN_ON_LIGHT_CYAN 187 // Светло-голубой на светло-голубом
#define LIGHT_RED_ON_LIGHT_CYAN 188 // Светло-красный на светло-голубом
#define LIGHT_MAGENTA_ON_LIGHT_CYAN 189 // Светло-магентовый на светло-голубом
#define YELLOW_ON_LIGHT_CYAN 190 // Желтый на светло-голубом
#define WHITE_ON_LIGHT_CYAN 191 // Белый на светло-голубом

#define BLACK_ON_LIGHT_RED 192 // Черный на светло-красном
#define BLUE_ON_LIGHT_RED 193 // Синий на светло-красном
#define GREEN_ON_LIGHT_RED 194 // Зеленый на светло-красном
#define CYAN_ON_LIGHT_RED 195 // Голубой на светло-красном
#define RED_ON_LIGHT_RED 196 // Красный на светло-красном
#define MAGENTA_ON_LIGHT_RED 197 // Магента на светло-красном
#define BROWN_ON_LIGHT_RED 198 // Коричневый на светло-красном
#define LIGHT_GRAY_ON_LIGHT_RED 199 // Светло-серый на светло-красном
#define DARK_GRAY_ON_LIGHT_RED 200 // Темно-серый на светло-красном
#define LIGHT_BLUE_ON_LIGHT_RED 201 // Светло-синий на светло-красном
#define LIGHT_GREEN_ON_LIGHT_RED 202 // Светло-зеленый на светло-красном
#define LIGHT_CYAN_ON_LIGHT_RED 203 // Светло-голубой на светло-красном
#define LIGHT_RED_ON_LIGHT_RED 204 // Светло-красный на светло-красном
#define LIGHT_MAGENTA_ON_LIGHT_RED 205 // Светло-магентовый на светло-красном
#define YELLOW_ON_LIGHT_RED 206 // Желтый на светло-красном
#define WHITE_ON_LIGHT_RED 207 // Белый на светло-красном

#define BLACK_ON_LIGHT_MAGENTA 208 // Черный на светло-магентовом
#define BLUE_ON_LIGHT_MAGENTA 209 // Синий на светло-магентовом
#define GREEN_ON_LIGHT_MAGENTA 210 // Зеленый на светло-магентовом
#define CYAN_ON_LIGHT_MAGENTA 211 // Голубой на светло-магентовом
#define RED_ON_LIGHT_MAGENTA 212 // Красный на светло-магентовом
#define MAGENTA_ON_LIGHT_MAGENTA 213 // Магента на светло-магентовом
#define BROWN_ON_LIGHT_MAGENTA 214 // Коричневый на светло-магентовом
#define LIGHT_GRAY_ON_LIGHT_MAGENTA 215 // Светло-серый на светло-магентовом
#define DARK_GRAY_ON_LIGHT_MAGENTA 216 // Темно-серый на светло-магентовом
#define LIGHT_BLUE_ON_LIGHT_MAGENTA 217 // Светло-синий на светло-магентовом
#define LIGHT_GREEN_ON_LIGHT_MAGENTA 218 // Светло-зеленый на светло-магентовом
#define LIGHT_CYAN_ON_LIGHT_MAGENTA 219 // Светло-голубой на светло-магентовом
#define LIGHT_RED_ON_LIGHT_MAGENTA 220 // Светло-красный на светло-магентовом
#define LIGHT_MAGENTA_ON_LIGHT_MAGENTA 221 // Светло-магентовый на светло-магентовом
#define YELLOW_ON_LIGHT_MAGENTA 222 // Желтый на светло-магентовом
#define WHITE_ON_LIGHT_MAGENTA 223 // Белый на светло-магентовом

#define BLACK_ON_YELLOW 224 // Черный на желтом
#define BLUE_ON_YELLOW 225 // Синий на желтом
#define GREEN_ON_YELLOW 226 // Зеленый на желтом
#define CYAN_ON_YELLOW 227 // Голубой на желтом
#define RED_ON_YELLOW 228 // Красный на желтом
#define MAGENTA_ON_YELLOW 229 // Магента на желтом
#define BROWN_ON_YELLOW 230 // Коричневый на желтом
#define LIGHT_GRAY_ON_YELLOW 231 // Светло-серый на желтом
#define DARK_GRAY_ON_YELLOW 232 // Темно-серый на желтом
#define LIGHT_BLUE_ON_YELLOW 233 // Светло-синий на желтом
#define LIGHT_GREEN_ON_YELLOW 234 // Светло-зеленый на желтом
#define LIGHT_CYAN_ON_YELLOW 235 // Светло-голубой на желтом
#define LIGHT_RED_ON_YELLOW 236 // Светло-красный на желтом
#define LIGHT_MAGENTA_ON_YELLOW 237 // Светло-магентовый на желтом
#define YELLOW_ON_YELLOW 238 // Желтый на желтом
#define WHITE_ON_YELLOW 239 // Белый на желтом

#define BLACK_ON_WHITE 240 // Черный на белом
#define BLUE_ON_WHITE 241 // Синий на белом
#define GREEN_ON_WHITE 242 // Зеленый на белом
#define CYAN_ON_WHITE 243 // Голубой на белом
#define RED_ON_WHITE 244 // Красный на белом
#define MAGENTA_ON_WHITE 245 // Магента на белом
#define BROWN_ON_WHITE 246 // Коричневый на белом
#define LIGHT_GRAY_ON_WHITE 247 // Светло-серый на белом
#define DARK_GRAY_ON_WHITE 248 // Темно-серый на белом
#define LIGHT_BLUE_ON_WHITE 249 // Светло-синий на белом
#define LIGHT_GREEN_ON_WHITE 250 // Светло-зеленый на белом
#define LIGHT_CYAN_ON_WHITE 251 // Светло-голубой на белом
#define LIGHT_RED_ON_WHITE 252 // Светло-красный на белом
#define LIGHT_MAGENTA_ON_WHITE 253 // Светло-магентовый на белом
#define YELLOW_ON_WHITE 254 // Желтый на белом
#define WHITE_ON_WHITE 255 // Белый на белом

#endif